stages:
  - renovate
  - publish

variables:
  NODE_IMAGE: node:20

############################
#Renovate job
############################
renovate:
  stage: renovate
  image: renovate/renovate:latest

  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: https://gitlab.com/api/v4
    LOG_LEVEL: info

  script:
    - renovate

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

############################
# Publish job
############################
publish:
  stage: publish
  image: $NODE_IMAGE

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - package.json
        - package-lock.json

  before_script:
    - npm ci

    # GitLab registry auth
    - echo "@dwp-govuk:registry=https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/" > .npmrc
    - echo "//gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc

  script:
    # Auto bump version (patch by default)
    - npm version patch --no-git-tag-version

    # Publish package
    - npm publish --registry https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/