stages:
  - publish
  - update

publish:
  stage: publish
  script:
    - npm ci
    - npm publish --registry https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/
  only:
    - tags

update-prototypes:
  stage: update
  script:
    - npm ci
    - node scripts/update-prototypes.js
  only:
    - tags
